#!/bin/bash
printf '%o\n' "$((5#$(echo $WATER | tr 'water' '01234')+5#$(echo $STIR | tr 'stir.' '01234')))"

printf '%o\n' "$((echo 253016754 | tr 'behlnort' '01234567'))"
echo 253016754 | tr '01234567' 'behlnort'

printf echo ('%o\n' "$((5#$(echo $WATER | tr 'water' '01234')+5#$(echo $STIR | tr 'stir.' '01234')))") | | tr '01234567' 'behlnort' 
